name: Deploy docker image

on:
  push:
    branches:
      - 'master'

jobs:

  build_docker_image:
    runs-on: ubuntu-18.04
    steps:

#     Build JAR:
      - uses: actions/checkout@v1
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Maven Package
        run: mvn -B clean compile package -DskipTests

#     Set global environment variables:
      - name: set global env
        id: global_env
#       переменную IMAGE_NAME формируем из названия репозитория
#                       "owner/repo-name"
#       берем все что после   /  чтобы задать имя образа
#       set-output выставляет переменную в этом шаге
        run: |
          REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')
          echo "::set-output name=IMAGE_NAME::${REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::ghcr.io/${REPOSITORY}"

#     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      - name: Docker login
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.PAT}}

#     Publish image to github package repository:
      - name: Publish image
        run: docker push "${{steps.global_env.outputs.DOCKERHUB_IMAGE_NAME}}"
      - name: Deploy to Docker-compose
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DOCKER_HOST }}
          privateKey: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          username: ${{ secrets.DOCKER_USER }}
          command: cd ~/bothosting && docker-compose pull && docker-compose down && docker-compose up -d
