name: "Auto-assign themes to PR"

on:
  - pull_request

jobs:
  assign:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}